#pragma once
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef enum _neoRADIO2AIN_EnableSetting {
	NEORADIO2AIN_CONFIG_DISABLE          = 0x00,
	NEORADIO2AIN_CONFIG_LOWRANGE         = 0x01,
	NEORADIO2AIN_CONFIG_LOWRANGE_500MV   = 0x02,
	NEORADIO2AIN_CONFIG_LOWRANGE_1000MV  = 0x03,
	NEORADIO2AIN_CONFIG_LOWRANGE_2000MV  = 0x04,
	NEORADIO2AIN_CONFIG_LOWRANGE_4000MV  = 0x05,
	NEORADIO2AIN_CONFIG_LOWRANGE_AUTO    = 0x06,
	NEORADIO2AIN_CONFIG_HIGHRANGE_2V     = 0x07,
	NEORADIO2AIN_CONFIG_HIGHRANGE_4V     = 0x08,
	NEORADIO2AIN_CONFIG_HIGHRANGE_8V     = 0x09,
	NEORADIO2AIN_CONFIG_HIGHRANGE_16V    = 0x0A,
	NEORADIO2AIN_CONFIG_HIGHRANGE_32V    = 0x0B,
	NEORADIO2AIN_CONFIG_HIGHRANGE_40V    = 0x0C,
	NEORADIO2AIN_CONFIG_HIGHRANGE_AUTO   = 0x0D,
} neoRADIO2AIN_EnableSetting;

#ifdef __cplusplus
}
#endif
